### ISSUE TITLE
Fix go.mod

### ISSUE THREAD

**Issue by kyeeego** [mhale/smtpd#25]
Hello! I really want to use this package in my project, but there is one major problem: it's impossible to use this package in go.mod file in my project because of package and module different names ("github.com/mhale/smtpd" and "github.com/prologic/smtpd" respectively), so go.mod can't find module to use. Would be awesome if you fixed this!

**Comment by mhale** [comment]
Sorry about that, it's fixed now.

**Comment by kyeeego** [comment]
Thank you! But I'm still getting this error:
```
go get package failed: err: exit status 1: stderr: go: finding module for package github.com/mhale/smtpd
go: found github.com/mhale/smtpd in github.com/mhale/smtpd v0.0.0-20210126072446-bc6803176f22
go: github.com/mhale/smtpd: github.com/mhale/smtpd@v0.0.0-20210126072446-bc6803176f22: parsing go.mod:
	module declares its path as: github.com/prologic/smtpd
	        but was required as: github.com/mhale/smtpd
```
I don't know whose this problem is and how to fix, can you help me please

**Comment by kyeeego** [comment]
Never mind. I didn't delete actually module at first lol. Now it all works. Thank you again and sorry gor bothering!
